Check if a lightbulb has fullcolorsupport
hthiery/python-fritzhome pull request #105
Opened 2024-10-25 08:17 UTC by flabbamann

If `fullcolorsupport` is set, we can use `setunmappedcolor` for free color selection. This was not documented at the time I implemented the free color selection.

2025-01-19 12:16 UTC, mib1185 requested changes

2025-01-19 12:16 UTC, mib1185 commented on pyfritzhome/devicetypes/fritzhomedevicelightbulb.py
> +                self.fullcolorsupport = colorcontrol_element.attrib.get(
we should use the `self.get_node_value_as_int_as_bool()` method here, so we get a bool out of it

2025-01-20 13:44 UTC, flabbamann commented on pyfritzhome/devicetypes/fritzhomedevicelightbulb.py
> +                self.fullcolorsupport = colorcontrol_element.attrib.get(
We can't use `get_node_value_as_int_as_bool()` here, as this is not a node value but an attribute. But you are right, that it should be a `bool`.

2025-01-25 16:20 UTC, mib1185 commented on tests/test_fritzhomedevicelightbulb.py
> +        assert device.fullcolorsupport is False
```suggestion
        assert not device.fullcolorsupport
```

2025-01-25 16:56 UTC, mib1185 approved these changes
LGTM, thx @flabbamann :+1:

2025-01-25 16:56 UTC, mib1185 commented
there are conflicts, please resolve them before we can merge this PR

2025-01-26 19:43 UTC, flabbamann commented
Hm, Githubs _new merge experience_ shows no conflicts, the _classic merge experience_ does...
Rebased to master.

2025-01-26 21:18 UTC, merged